### ISSUE TITLE
java.lang.IllegalStateException: Fail to save the PMD configuration (.scannerwork/pmd-unit-tests.xml (Too many open files))

### ISSUE THREAD

**Issue by varghgeorge** [jborgers/sonar-pmd#39]
I am getting an error on PMD. How do we resolve this?

ERROR: Error during SonarQube Scanner execution
org.sonar.api.utils.XmlParserException: java.lang.IllegalStateException: Fail to save the PMD configuration
	at org.sonar.plugins.pmd.PmdSensor.analyse(PmdSensor.java:72)
	at org.sonar.scanner.phases.SensorsExecutor.executeSensor(SensorsExecutor.java:57)
	at org.sonar.scanner.phases.SensorsExecutor.execute(SensorsExecutor.java:49)
	at org.sonar.scanner.phases.AbstractPhaseExecutor.execute(AbstractPhaseExecutor.java:78)
	at org.sonar.scanner.scan.ModuleScanContainer.doAfterStart(ModuleScanContainer.java:175)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:143)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:128)
	at org.sonar.scanner.scan.ProjectScanContainer.scan(ProjectScanContainer.java:262)
	at org.sonar.scanner.scan.ProjectScanContainer.scanRecursively(ProjectScanContainer.java:257)
	at org.sonar.scanner.scan.ProjectScanContainer.doAfterStart(ProjectScanContainer.java:247)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:143)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:128)
	at org.sonar.scanner.task.ScanTask.execute(ScanTask.java:47)
	at org.sonar.scanner.task.TaskContainer.doAfterStart(TaskContainer.java:86)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:143)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:128)
	at org.sonar.scanner.bootstrap.GlobalContainer.executeTask(GlobalContainer.java:118)
	at org.sonar.batch.bootstrapper.Batch.executeTask(Batch.java:117)
	at org.sonarsource.scanner.api.internal.batch.BatchIsolatedLauncher.execute(BatchIsolatedLauncher.java:63)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.sonarsource.scanner.api.internal.IsolatedLauncherProxy.invoke(IsolatedLauncherProxy.java:60)
	at com.sun.proxy.$Proxy0.execute(Unknown Source)
	at org.sonarsource.scanner.api.EmbeddedScanner.doExecute(EmbeddedScanner.java:233)
	at org.sonarsource.scanner.api.EmbeddedScanner.runAnalysis(EmbeddedScanner.java:151)
	at org.sonarsource.scanner.cli.Main.runAnalysis(Main.java:123)
	at org.sonarsource.scanner.cli.Main.execute(Main.java:77)
	at org.sonarsource.scanner.cli.Main.main(Main.java:61)
Caused by: java.lang.IllegalStateException: Fail to save the PMD configuration
	at org.sonar.plugins.pmd.PmdConfiguration.dumpXmlRuleSet(PmdConfiguration.java:59)
	at org.sonar.plugins.pmd.PmdExecutor.createRulesets(PmdExecutor.java:128)
	at org.sonar.plugins.pmd.PmdExecutor.executeRules(PmdExecutor.java:111)
	at org.sonar.plugins.pmd.PmdExecutor.executePmd(PmdExecutor.java:91)
	at org.sonar.plugins.pmd.PmdExecutor.execute(PmdExecutor.java:75)
	at org.sonar.plugins.pmd.PmdSensor.analyse(PmdSensor.java:67)
	... 29 more
Caused by: java.io.FileNotFoundException: <project folder>/.scannerwork/pmd-unit-tests.xml (Too many open files)
	at java.io.FileOutputStream.open0(Native Method)
	at java.io.FileOutputStream.open(FileOutputStream.java:270)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
	at com.google.common.io.Files$2.getOutput(Files.java:132)
	at com.google.common.io.Files$2.getOutput(Files.java:129)
	at com.google.common.io.CharStreams$3.getOutput(CharStreams.java:111)
	at com.google.common.io.CharStreams$3.getOutput(CharStreams.java:108)
	at com.google.common.io.CharStreams.write(CharStreams.java:128)
	at com.google.common.io.Files.write(Files.java:335)
	at com.google.common.io.Files.write(Files.java:306)
	at org.sonar.plugins.pmd.PmdConfiguration.writeToWorkingDirectory(PmdConfiguration.java:95)
	at org.sonar.plugins.pmd.PmdConfiguration.dumpXmlRuleSet(PmdConfiguration.java:53)

**Comment by jborgers** [comment]
Old versions. Assuming not relevant anymore.
