### ISSUE TITLE
Request: Support SonarQube 10.5 in new release 3.5.1

### ISSUE THREAD

**Issue by jborgers** [jborgers/sonar-pmd#459]
New released 3.5.0 runs fine in SQ 10.4. In SQ 10.5 there is an API change which breaks things:

```
[ERROR] Failed to execute goal org.sonarsource.scanner.maven:sonar-maven-plugin:3.9.1.2184:sonar (default-cli) on project bk-services: Unable to load components interface org.sonar.api.batch.sensor.Sensor: Error creating bean with name 'ClassRealm{pmd}-org.sonar.plugins.pmd.PmdSensor': Unsatisfied dependency expressed through constructor parameter 1; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'ClassRealm{pmd}-org.sonar.plugins.pmd.PmdExecutor': Resolution of declared constructors on bean Class [org.sonar.plugins.pmd.PmdExecutor] from ClassLoader [ClassRealm{pmd}] failed; nested exception is java.lang.NoClassDefFoundError: org/sonar/plugins/java/api/JavaResourceLocator: org.sonar.plugins.java.api.JavaResourceLocator -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
Exception in thread "Thread-1" java.lang.NoClassDefFoundError: ch/qos/logback/classic/spi/ThrowableProxy
	at ch.qos.logback.classic.spi.LoggingEvent.<init>(LoggingEvent.java:145)
	at ch.qos.logback.classic.Logger.buildLoggingEventAndAppend(Logger.java:424)
	at ch.qos.logback.classic.Logger.filterAndLog_0_Or3Plus(Logger.java:386)
	at ch.qos.logback.classic.Logger.error(Logger.java:543)
	at org.eclipse.jgit.internal.util.ShutdownHook.cleanup(ShutdownHook.java:87)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: java.lang.ClassNotFoundException: ch.qos.logback.classic.spi.ThrowableProxy
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:445)
	at org.sonarsource.scanner.api.internal.IsolatedClassloader.loadClass(IsolatedClassloader.java:82)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
	... 6 more

```

**Comment by jborgers** [comment]
Basically: java.lang.NoClassDefFoundError: org/sonar/plugins/java/api/JavaResourceLocator: org.sonar.plugins.java.api.JavaResourceLocator

The last exception is another non-critical issue which seems to be encountered by many.

**Comment by jborgers** [comment]
See #421

**Comment by jborgers** [comment]
Solved

**Comment by jborgers** [comment]
3.5.1-beta pre-release is published to try-out.
