### ISSUE TITLE
 The plugin 'java' required by 'findbugs' is missing

### ISSUE THREAD

**Issue by kzycoker** [jborgers/sonar-pmd#466]
version:sonarqube:7.8-community

java.lang.IllegalStateException: Unable to load installed plugins
        at org.sonar.server.plugins.InstalledPluginReferentialFactory.start(InstalledPluginReferentialFactory.java:40)
        at org.sonar.core.platform.StartableCloseableSafeLifecyleStrategy.start(StartableCloseableSafeLifecyleStrategy.java:40)
        at org.picocontainer.injectors.AbstractInjectionFactory$LifecycleAdapter.start(AbstractInjectionFactory.java:84)
        at org.picocontainer.behaviors.AbstractBehavior.start(AbstractBehavior.java:169)
        at org.picocontainer.behaviors.Stored$RealComponentLifecycle.start(Stored.java:132)
        at org.picocontainer.behaviors.Stored.start(Stored.java:110)
        at org.picocontainer.DefaultPicoContainer.potentiallyStartAdapter(DefaultPicoContainer.java:1016)
        at org.picocontainer.DefaultPicoContainer.startAdapters(DefaultPicoContainer.java:1009)
        at org.picocontainer.DefaultPicoContainer.start(DefaultPicoContainer.java:767)
        at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:135)
        at org.sonar.ce.container.ComputeEngineContainerImpl.startLevel2(ComputeEngineContainerImpl.java:217)
        at org.sonar.ce.container.ComputeEngineContainerImpl.start(ComputeEngineContainerImpl.java:187)
        at org.sonar.ce.ComputeEngineImpl.startup(ComputeEngineImpl.java:45)
        at org.sonar.ce.app.CeServer$CeMainThread.attemptStartup(CeServer.java:160)
        at org.sonar.ce.app.CeServer$CeMainThread.run(CeServer.java:138)
Caused by: org.sonar.updatecenter.common.exception.PluginNotFoundException: The plugin 'java' required by 'findbugs' is missing.
        at org.sonar.updatecenter.common.PluginReferential.addOutgoingDependency(PluginReferential.java:140)
        at org.sonar.updatecenter.common.PluginReferentialManifestConverter.lambda$fromPluginManifests$0(PluginReferentialManifestConverter.java:60)
        at java.lang.Iterable.forEach(Iterable.java:75)
        at org.sonar.updatecenter.common.PluginReferentialManifestConverter.fromPluginManifests(PluginReferentialManifestConverter.java:56)
        at org.sonar.server.plugins.PluginReferentialMetadataConverter.getInstalledPluginReferential(PluginReferentialMetadataConverter.java:45)
        at org.sonar.server.plugins.InstalledPluginReferentialFactory.init(InstalledPluginReferentialFactory.java:54)
        at org.sonar.server.plugins.InstalledPluginReferentialFactory.start(InstalledPluginReferentialFactory.java:38)
        ... 14 common frames omitted
Caused by: java.util.NoSuchElementException: Unable to find plugin with key java
        at org.sonar.updatecenter.common.PluginReferential.findPlugin(PluginReferential.java:87)
        at org.sonar.updatecenter.common.PluginReferential.addOutgoingDependency(PluginReferential.java:126)
        ... 20 common frames omitted

**Comment by jborgers** [comment]
Hi @kzycoker you are reporting a problem with the findbugs plugin, this is the place for the pmd plugin.
Therefore, I am closing this issue.
